name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-projects/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform-projects/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[profile dev]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "[profile prod]" >> ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "[dev]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> ~/.aws/credentials
          echo "[prod]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> ~/.aws/credentials

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-projects/${{ github.event.repository.name }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform-projects/${{ github.event.repository.name }}

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan
        working-directory: terraform-projects/${{ github.event.repository.name }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve plan.tfplan
        working-directory: terraform-projects/${{ github.event.repository.name }}

