name: Terraform CI

on:
  push:
    branches:
      - main
    paths:
      - 'terraform-projects/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform-projects/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[profile dev]" > ~/.aws/config
          echo "region = us-east-2" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "[profile prod]" >> ~/.aws/config
          echo "region = us-east-2" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "[dev]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}" >> ~/.aws/credentials
          echo "[prod]" >> ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> ~/.aws/credentials

# ... (other steps)

      - name: Find changed Terraform directory
        id: find_changed_dir
        run: |
          echo "Checking for changes in terraform-projects/"
          for dir in terraform-projects/*; do
            echo "Checking directory: $dir"  
            # Get the base SHA correctly for both pull_request and push events
            base_sha="${{ github.event.pull_request.base.sha || github.event.before }}"

            if [[ -n $(git diff --name-only $base_sha ${{ github.sha }} "$dir") ]]; then
              echo "directory=$dir" >> $GITHUB_OUTPUT
              break
            fi
          done


# ... (rest of your workflow using steps.find_changed_dir.outputs.directory)


      - name: Terraform Init
        working-directory: ${{ steps.find_changed_dir.outputs.directory }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ steps.find_changed_dir.outputs.directory }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ steps.find_changed_dir.outputs.directory }}
        run: terraform plan -out=plan.tfplan  -lock=false 
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ steps.find_changed_dir.outputs.directory }}
        run: terraform apply -auto-approve plan.tfplan -lock=false 
        
#### Hopefull workflow should look good"