name: Terraform CI with OIDC

on:
  push:
    branches:
      - '**'  
    paths:
      - "terraform-projects/**"
  pull_request:
    branches:
      - '**' 
    paths:
      - "terraform-projects/**"

permissions:
  id-token: write
  contents: read

env: 
  TF_IN_AUTOMATION: 1
  AWS_REGION: us-east-2 
  AWS_ROLE_ARN: arn:aws:iam::975050274549:role/mygithubrole

jobs:
  terraform:
    name: Terraform ${{ matrix.terraform_folder }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_folder: ["terraform-projects/dev", "terraform-projects/prod"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Set AWS Environment
        run: |
          if [[ "${{ matrix.terraform_folder }}" == "terraform-projects/dev" ]]; then
            echo "AWS_ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${{ matrix.terraform_folder }}" == "terraform-projects/prod" ]]; then
            echo "AWS_ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "Invalid terraform_folder"
            exit 1
          fi 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2  # Use the latest version (v2)
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Find Changed Directories
        id: find_changed_dirs
        run: |
          # ... (rest of the find_changed_dirs step is unchanged)
          
      - name: Terraform Init, Validate, Plan
        if: steps.find_changed_dirs.outputs.changed_dirs != ''
        run: |
          # ... (rest of the Terraform steps are unchanged)
